apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: <AWS 계정 ID>.dkr.ecr.ap-northeast-2.amazonaws.com/my-app
  newName: <AWS 계정 ID>.dkr.ecr.ap-northeast-2.amazonaws.com/my-app
  newTag: 665f2f2b
resources:
- ../../base
patchesStrategicMerge:
- myapp-deployment-patch.yaml

